apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: order-tls-cert
  namespace: default
  annotations:
    # cert-manager.io/issue-temporary-certificate: "true"
spec:
  dnsNames:
    - order-service.avinashupadhyaya.live
  secretName: order-tls-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer