apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: order-service.avinashupadhyaya.live
  name: service-order
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: order-service